### ISSUE TITLE
Add support for repr structs

### ISSUE THREAD

**Issue by Rexagon** [Rexagon/opg#1]
Currently simple C-like enums are serialized as string enums:

```rust
#[derive(Serialize)]
enum Test {
    First = 1,
    Second = 2,
}
```

```yaml
type: string
enum:
  - First
  - Second
example: First
```

It should be something like this:

```yaml
oneOf:
  - type: integer
    description: First variant
    example: 1
  - type: integer
    description: Second variant
    example: 2
```
